export const mockClinics = [
  {
    id: 1,
    name: 'Serenity Wellness Center',
    distance: '0.8 miles',
    address: '123 Healing Street, Anytown, CA 94110',
    phone: '(555) 123-4567',
    website: 'https://example.com/serenity',
    specialties: ['Anxiety', 'Depression', 'Trauma'],
    insuranceAccepted: ['Blue Cross', 'Aetna', 'Kaiser'],
    rating: 4.8,
    reviews: 126,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Serenity+Wellness',
    description:
      'A warm and welcoming space offering evidence-based therapy services for individuals, couples, and families. Our team specializes in cognitive behavioral therapy and mindfulness-based approaches.',
  },
  {
    id: 2,
    name: 'Mindful Therapy Group',
    distance: '1.2 miles',
    address: '456 Balance Avenue, Anytown, CA 94110',
    phone: '(555) 234-5678',
    website: 'https://example.com/mindful',
    specialties: ['Mindfulness', 'Relationship Issues', 'Stress Management'],
    insuranceAccepted: ['Blue Cross', 'United Healthcare', 'Cigna'],
    rating: 4.6,
    reviews: 98,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Mindful+Therapy',
    description:
      'Our collaborative team of therapists focuses on helping clients develop mindfulness skills while addressing a wide range of mental health concerns. We offer both in-person and virtual sessions.',
  },
  {
    id: 3,
    name: 'Harmony Counseling Services',
    distance: '1.5 miles',
    address: '789 Inner Peace Lane, Anytown, CA 94110',
    phone: '(555) 345-6789',
    website: 'https://example.com/harmony',
    specialties: ['Grief', 'Life Transitions', 'Self-Esteem'],
    insuranceAccepted: ['Medicare', 'Aetna', 'Anthem'],
    rating: 4.9,
    reviews: 203,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Harmony+Counseling',
    description:
      'A compassionate therapy practice dedicated to helping individuals find peace and emotional well-being. Our therapists are trained in various modalities including psychodynamic therapy and EMDR.',
  },
  {
    id: 4,
    name: 'Renewal Behavioral Health',
    distance: '2.3 miles',
    address: '101 Recovery Road, Anytown, CA 94110',
    phone: '(555) 456-7890',
    website: 'https://example.com/renewal',
    specialties: ['Addiction', 'Anxiety', 'Depression'],
    insuranceAccepted: ['Blue Shield', 'Cigna', 'Medicare'],
    rating: 4.7,
    reviews: 157,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Renewal+Health',
    description:
      'Specializing in addiction recovery and dual diagnosis treatment, our center offers integrated care that addresses both substance use and mental health concerns. We provide individualized treatment plans and group support.',
  },
  {
    id: 5,
    name: 'Tranquil Waters Therapy',
    distance: '2.8 miles',
    address: '222 Stillness Street, Anytown, CA 94110',
    phone: '(555) 567-8901',
    website: 'https://example.com/tranquil',
    specialties: ['PTSD', 'Trauma', 'Anxiety Disorders'],
    insuranceAccepted: ['Kaiser', 'United Healthcare', 'Blue Cross'],
    rating: 4.5,
    reviews: 89,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Tranquil+Waters',
    description:
      'Our practice specializes in trauma-informed care and provides a safe environment for healing. We offer somatic experiencing, EMDR, and other evidence-based trauma therapies.',
  },
  {
    id: 6,
    name: 'Insight Psychological Services',
    distance: '3.1 miles',
    address: '333 Reflection Drive, Anytown, CA 94110',
    phone: '(555) 678-9012',
    website: 'https://example.com/insight',
    specialties: ['Depression', 'Anxiety', 'Relationship Issues'],
    insuranceAccepted: ['Anthem', 'Blue Shield', 'Cigna'],
    rating: 4.4,
    reviews: 112,
    imageUrl: 'https://placehold.co/600x300/4CAF50/FFFFFF/png?text=Insight+Services',
    description:
      'Our diverse team of psychologists and therapists provides comprehensive mental health care for individuals and couples. We specialize in evidence-based approaches including CBT and acceptance and commitment therapy.',
  },
];
